apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  containers:
    - args:
        - start-dev
        - --import-realm
        - --health-enabled=true
      env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_PASSWORD
          value: root
        - name: KC_DB_URL_DATABASE
          value: keycloak_db
        - name: KC_DB_URL_HOST
          value: keycloak-pg-database
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_USERNAME
          value: postgres
        - name: KC_FEATURES
          value: token-exchange,admin-fine-grained-authz
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
      image: quay.io/keycloak/keycloak:26.0.7
      name: cab-keycloak
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /opt/keycloak/data/import
          name: keycloak-cm0
  restartPolicy: OnFailure
  volumes:
    - configMap:
        name: keycloak-cm0
      name: keycloak-cm0
