spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/cab-aggregator-realm}
  messages:
    basename:
      encoding: "UTF-8"
      error-causes: "classpath:error_causes"
      validation-errors: "classpath:validation_errors"
      messages: "classpath:messages"
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app:
  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:cab-aggregator-realm}
    grant-type: ${KEYCLOAK_GRANT_TYPE:client_credentials}
    admin:
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
      client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:DvvioL4dre9nKOIzPrgaZm6VqyJODevD}
    client:
      client-id: ${KEYCLOAK_USER_CLIENT_ID:cab-aggregator-client}
      client-secret: ${KEYCLOAK_USER_CLIENT_SECRET:NsaeQ20BK7DL4hdWxAzx0iCzbUHjw1OL}
  kafka:
    topics:
      passenger:
        name: ${KAFKA_TOPIC_PASSENGER_NAME:passenger-topic}
        partitions: ${KAFKA_TOPIC_PASSENGER_PARTITIONS:1}
        replicas: ${KAFKA_TOPIC_PASSENGER_REPLICAS:1}
      driver:
        name: ${KAFKA_TOPIC_DRIVER_NAME:driver-topic}
        partitions: ${KAFKA_TOPIC_DRIVER_PARTITIONS:1}
        replicas: ${KAFKA_TOPIC_DRIVER_REPLICAS:1}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: framework
