apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  containers:
    - env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        - name: ELASTICSEARCH_PASSWORD
          value: elastic
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
          value: "true"
      image: kibana:7.14.2
      livenessProbe:
        exec:
          command:
            - curl --silent --fail http://localhost:5601/api/status || exit 1
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
      name: cab-kibana
      ports:
        - containerPort: 5601
          protocol: TCP
  restartPolicy: OnFailure
