apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  containers:
    - env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
        - name: LOGSTASH_HOSTPORT
          value: logstash:5000
        - name: OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
          value: http://keycloak:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs
        - name: SERVER_PORT
          value: "8090"
        - name: ZIPKIN_TRACING_ENDPOINT
          value: http://zipkin:9411/api/v2/spans
      image: cab-api-gateway:1.0.0
      livenessProbe:
        exec:
          command:
            - wget --spider --quiet http://localhost:8090/actuator/health && wget -qO- http://localhost:8090/actuator/health | grep UP || exit 1
        failureThreshold: 5
        initialDelaySeconds: 20
        periodSeconds: 20
        timeoutSeconds: 5
      name: cab-api-gateway
      ports:
        - containerPort: 8090
          protocol: TCP
  restartPolicy: OnFailure
