apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: cab-eureka-server
          image: cab-eureka-server:1.0.0
          envFrom:
            - configMapRef:
                name: eureka-server-config
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - wget --spider --quiet http://localhost:8761/actuator/health && wget -qO- http://localhost:8761/actuator/health | grep UP || exit 1
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          ports:
            - containerPort: 8761
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
