apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  datasource.yml: |
    apiVersion: 1
    
    datasources:
      - name: Prometheus
        label: Prometheus
        type: prometheus
        access: proxy
        url: http://host.docker.internal:9090
        isDefault: true
        editable: false
