apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: cab-grafana
          image: grafana/grafana:11.4.0
          envFrom:
            - configMapRef:
                name: grafana-config
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl --fail -s http://localhost:3000/api/health || exit 1
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasource-config
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboard-config
      volumes:
        - name: grafana-datasource-config
          configMap:
            name: grafana-datasource-config
        - name: grafana-dashboard-config
          configMap:
            name: grafana-dashboard-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
