apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  containers:
    - env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: interval
          value: 10s
        - name: retries
          value: "5"
        - name: start_period
          value: 10s
        - name: test
          value: curl --fail -s http://localhost:3000/api/health || exit 1
        - name: timeout
          value: 5s
      image: grafana/grafana:11.4.0
      name: cab-grafana
      ports:
        - containerPort: 3000
          protocol: TCP
  restartPolicy: OnFailure
