INSERT INTO weather_coefficients (weather, price_coefficient)
VALUES
    ('Sunny', 1.00),
    ('Clear', 1.00),
    ('Partly cloudy', 1.02),
    ('Cloudy', 1.05),
    ('OverCast', 1.08),
    ('Mist', 1.05),
    ('Patchy rain possible', 1.09),
    ('Patchy snow possible', 1.06),
    ('Patchy sleet possible', 1.07),
    ('Patchy freezing drizzle possible', 1.10),
    ('Thundery outbreaks possible', 1.10),
    ('Blowing snow', 1.20),
    ('Blizzard', 1.20),
    ('Fog', 1.08),
    ('Freezing fog', 1.10),
    ('Patchy light drizzle', 1.05),
    ('Light drizzle', 1.08),
    ('Freezing drizzle', 1.15),
    ('Heavy freezing drizzle', 1.20),
    ('Patchy light rain', 1.10),
    ('Light rain', 1.15),
    ('Moderate rain at times', 1.12),
    ('Moderate rain', 1.17),
    ('Heavy rain at times', 1.17),
    ('Heavy rain', 1.20),
    ('Light freezing rain', 1.12),
    ('Moderate or heavy freezing rain', 1.20),
    ('Light sleet', 1.07),
    ('Moderate or heavy sleet', 1.15),
    ('Patchy light snow', 1.05),
    ('Light snow', 1.07),
    ('Patchy moderate snow', 1.09),
    ('Moderate snow', 1.12),
    ('Patchy heavy snow', 1.15),
    ('Heavy snow', 1.20),
    ('Ice pellets', 1.30),
    ('Light rain shower', 1.15),
    ('Moderate or heavy rain shower', 1.20),
    ('Torrential rain shower', 1.30),
    ('Light sleet showers', 1.20),
    ('Moderate or heavy sleet showers', 1.30),
    ('Light snow showers', 1.10),
    ('Moderate or heavy snow showers', 1.20),
    ('Light showers of ice pellets', 1.20),
    ('Moderate or heavy showers of ice pellets', 1.30),
    ('Patchy light rain with thunder', 1.15),
    ('Moderate or heavy rain with thunder', 1.25),
    ('Patchy light snow with thunder', 1.15),
    ('Moderate or heavy snow with thunder', 1.25);
