apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: keycloak-pg-database
  name: keycloak-pg-database
spec:
  containers:
    - env:
        - name: POSTGRES_DB
          value: keycloak_db
        - name: POSTGRES_PASSWORD
          value: root
        - name: POSTGRES_USER
          value: postgres
      image: postgres:17
      livenessProbe:
        exec:
          command:
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
        failureThreshold: 5
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 5
      name: cab-keycloak-pg-database
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: keycloak-pg-database-data
  restartPolicy: OnFailure
  volumes:
    - name: keycloak-pg-database-data
      persistentVolumeClaim:
        claimName: keycloak-pg-database-data
