apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  containers:
    - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://127.0.0.1:9092
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: DOCKER_INTERNAL
        - name: KAFKA_LISTENERS
          value: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
      image: obsidiandynamics/kafka
      livenessProbe:
        exec:
          command:
            - kafka-topics --bootstrap-server localhost:29092 --list
        failureThreshold: 5
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
      name: cab-kafka
      ports:
        - containerPort: 9092
          protocol: TCP
  restartPolicy: OnFailure
