apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rating-mongo-database1
  name: rating-mongo-database1
spec:
  ports:
    - name: "27019"
      port: 27019
      targetPort: 27017
  selector:
    io.kompose.service: rating-mongo-database1
