apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: rating-mongo-database1-data
  name: rating-mongo-database1-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
