spring:
  application:
    name: rating-service
  messages:
    basename:
      encoding: "UTF-8"
      error-causes: "classpath:error_causes"
      messages: "classpath:messages"
  data:
    mongodb:
      uri: mongodb://${DB_HOSTPORT:localhost:27017}/${DB_NAME:rating_database}
      username: ${DB_USERNAME:mongo}
      password: ${DB_PASSWORD:root}
mongock:
  migration-scan-package: com.cabaggregator.ratingservice.migrations
  enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
server:
  port: ${SERVER_PORT:8086}
