spring:
  application:
    name: rating-service
  messages:
    basename:
      encoding: "UTF-8"
      error-causes: "classpath:error_causes"
      messages: "classpath:messages"
  data:
    mongodb:
      uri: mongodb://${DB_HOSTPORT:localhost:27018}/${DB_NAME:rating_database}
      username: ${DB_USERNAME:mongo}
      password: ${DB_PASSWORD:root}
      replica-set-name: ${DB_REPLICA_SET_NAME:rs1}
      database: ${DB_NAME:rating_database}
mongock:
  migration-scan-package: com.cabaggregator.ratingservice.migrations
  enabled: true
server:
  port: ${SERVER_PORT:8086}
