spring:
  application:
    name: price-calculation-service
  messages:
    basename:
      encoding: "UTF-8"
      error-causes: "classpath:error_causes"
      validation-errors: "classpath:validation_errors"
  datasource:
    url: jdbc:postgresql://${DB_HOSTPORT:localhost:5432}/${DB_NAME:price_calculation_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      database: ${REDIS_DATABASE:0}
app:
  weather:
    api-key: ${WEATHER_API_KEY}
  cache:
    ttl:
      fare-cache: ${FARE_CACHE_TTL:1440}
      weather-cache: ${WEATHER_CACHE_TTL:180}
  redis:
    key:
      prefix:
        cell-demand: ${REDIS_CELL_DEMAND_KEY_PREFIX:cell_demand:}
        cell: ${REDIS_CEL_KEY_PREFIX:cell:}
        ride: ${REDIS_RIDE_KEY_PREFIX:ride:}
      ttl: ${REDIS_DEMAND_KEY_TTL:10}
server:
  port: ${SERVER_PORT:8087}
