apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: cab-driver-service
          image: cab-driver-service:1.0.0
          envFrom:
            - configMapRef:
                name: driver-service-config
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - wget --spider --quiet http://localhost:8083/actuator/health && wget -qO- http://localhost:8083/actuator/health | grep UP || exit 1
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          ports:
            - containerPort: 8083
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  type: ClusterIP
  selector:
    app: driver-service
  ports:
    - port: 8083
      targetPort: 8083
