apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  containers:
    - image: openzipkin/zipkin
      livenessProbe:
        exec:
          command:
            - curl --silent --fail http://localhost:5601/api/health | grep UP || exit 1
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
      name: cab-zipkin
      ports:
        - containerPort: 9411
          protocol: TCP
  restartPolicy: OnFailure
