apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  containers:
    - image: zookeeper:3.7.0
      livenessProbe:
        exec:
          command:
            - nc -z 127.0.0.1 2181 || exit -1
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
      name: cab-zookeeper
      ports:
        - containerPort: 2181
          protocol: TCP
  restartPolicy: OnFailure
