apiVersion: v1
kind: ConfigMap
metadata:
  name: promo-code-service-config
data:
  DB_PASSWORD: "root"
  DB_URL: "promo-code-pg-database:5432/promo_code_database"
  DB_USERNAME: "postgres"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  LOGSTASH_URL: "logstash:5000"
  SERVER_PORT: "8085"
  ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
