apiVersion: apps/v1
kind: Deployment
metadata:
  name: promo-code-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promo-code-service
  template:
    metadata:
      labels:
        app: promo-code-service
    spec:
      containers:
        - name: cab-promo-code-service
          image: cab-promo-code-service:1.0.0
          envFrom:
            - configMapRef:
                name: promo-code-service-config
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - wget --spider --quiet http://localhost:8085/actuator/health && wget -qO- http://localhost:8085/actuator/health | grep UP || exit 1
            failureThreshold: 5
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          ports:
            - containerPort: 8085
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: promo-code-service
spec:
  type: ClusterIP
  selector:
    app: promo-code-service
  ports:
    - port: 8085
      targetPort: 8085
