apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  containers:
    - env:
        - name: REDIS_PASSWORD
          value: passwords
      image: redis:7.4-alpine
      livenessProbe:
        exec:
          command:
            - redis-cli ping
        failureThreshold: 5
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 5
      name: cab-redis-server
      ports:
        - containerPort: 6379
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: cab-redis-data
  restartPolicy: OnFailure
  volumes:
    - name: cab-redis-data
      persistentVolumeClaim:
        claimName: cab-redis-data
