apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  containers:
    - env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:29092
        - name: KEYCLOAK_ADMIN_CLIENT_ID
          value: admin-cli
        - name: KEYCLOAK_ADMIN_CLIENT_SECRET
          value: DvvioL4dre9nKOIzPrgaZm6VqyJODevD
        - name: KEYCLOAK_GRANT_TYPE
          value: client_credentials
        - name: KEYCLOAK_REALM
          value: cab-aggregator-realm
        - name: KEYCLOAK_SERVER_URL
          value: http://keycloak:8080
        - name: KEYCLOAK_USER_CLIENT_ID
          value: cab-aggregator-client
        - name: KEYCLOAK_USER_CLIENT_SECRET
          value: NsaeQ20BK7DL4hdWxAzx0iCzbUHjw1OL
        - name: LOGSTASH_HOSTPORT
          value: logstash:5000
        - name: SERVER_PORT
          value: "8081"
        - name: ZIPKIN_TRACING_ENDPOINT
          value: http://zipkin:9411/api/v2/spans
      image: cab-auth-service:1.0.0
      livenessProbe:
        exec:
          command:
            - wget --spider --quiet http://localhost:8081/actuator/health && wget -qO- http://localhost:8081/actuator/health | grep UP || exit 1
        failureThreshold: 5
        initialDelaySeconds: 20
        periodSeconds: 20
        timeoutSeconds: 5
      name: cab-auth-service
      ports:
        - containerPort: 8081
          protocol: TCP
  restartPolicy: OnFailure
