spring:
  application:
    name: eureka-server
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
logging:
  logstash:
    server: ${LOGSTASH_URL:localhost:5000}
server:
  port: ${SERVER_PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-port: ${SERVER_PORT:8761}
    service-url:
      default-zone: http://localhost:${SERVER_PORT:8761}/eureka
  instance:
    metadata-map:
      metrics.path: /actuator/prometheus
