apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  DB_PASSWORD: "root"
  DB_URL: "payment-pg-database:5432/payment_database"
  DB_USERNAME: "postgres"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  LOGSTASH_URL: "logstash:5000"
  SERVER_PORT: "8088"
  ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
