apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Utils\Kompose\bin\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  containers:
    - env:
        - name: ELASTIC_PASSWORD
          value: elastic
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        - name: discovery.type
          value: single-node
      image: elasticsearch:7.14.2
      livenessProbe:
        exec:
          command:
            - curl --silent --fail http://localhost:9200/_cluster/health || exit 1
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
      name: cab-elasticsearch
      ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
  restartPolicy: OnFailure
