apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: payment-pg-database-data
  name: payment-pg-database-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
